### ISSUE TITLE
Video Station 3.0.1-2067

### ISSUE THREAD

**Issue by garryde** [Wooden-Robot/documents-for-fun#17]
Video Station 3.0.1-2067
DSM 7.0-41890

视频点进去不会出现错误，但是一直在转圈圈无法加载

求适配

**Comment by gujiangjiang** [comment]
> 不好意思啊，手上没有 7.0 的设备

黑群7.0.1目前还算比较完美，可以试一下，没您这个工具自带的播放器毫无用处，哈哈哈

**Comment by gujiangjiang** [comment]
@garryde 您可以参考这个
https://zhuanlan.zhihu.com/p/393311059
